import {TouchableOpacity} from 'react-native';
export enum Routes {
  //App
  AUTH_NAVIGATOR = 'AUTH_NAVIGATOR',
  TABS_NAVIGATOR = 'TABS_NAVIGATOR',

  //TABS
  USER_NAVIGATOR = 'USER_NAVIGATOR',
  ROOM_NAVIGATOR = 'ROOM_NAVIGATOR',
  ROOM_CREATE_NAVIGATOR = 'ROOM_CREATE_NAVIGATOR',
  INVITES_NAVIGATOR = 'INVITES_NAVIGATOR',

  //AUTH
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',
  FINISH_SIGN_UP = 'FINISH_SIGN_UP',

  //PROFILE
  USER_LIST = 'USER_LIST',
  USER_DETAIL = 'USER_DETAIL',

  //ROOM
  ROOMS_LIST = 'ROOMS_LIST',
  ROOM_DETAIL = 'ROOMS_DETAIL',

  //ROOM_CREATE
  ROOM_CREATE = 'ROOM_CREATE',
}
